title: DevOps
description:  DevOps
theme: just-the-docs

url: https://1idejun.github.io

# Aux links for the upper right navigation
aux_links:
  "1idejun.github.io":
    - "//github.com/1idejun/1idejun.github.io"

